### ISSUE TITLE
Why no support for QL810W

### ISSUE THREAD

**Issue by eugenedw** [rdlabo-team/capacitor-brotherprint#13]
A prior version of this plugin provided support for QL-810W printers. 
The older version, however, did not build for Android, though it was working fine for iOS.
After upgrading to this latest version, I can no longer print on QL-810W and noticed these lines in the swift file for the plugin, hardcoding only the 820NWB:

```
let modelName: String = call.getString("modelName", "QL-820NWB")
let printerModel = BrotherModel.getModelName(from: modelName)
```

Is there any possibility of re-adding support for this printer?

**Comment by rdlabo** [comment]
The second argument of getString is the default value, so it differs from hardcoding. In fact, it is present in ModelName.

https://github.com/rdlabo-team/capacitor-brotherprint/blob/main/ios/Plugin/Model/PrinterModel.swift#L44-L45

Since the version has been upgraded to use Enum (*this is due to an upgrade of the Brother SDK), please refer to this page.

https://github.com/rdlabo-team/capacitor-brotherprint/blob/main/src/brother-printer.enum.ts#L26-L33

**Comment by eugenedw** [comment]
Thank you for the explanation.

I've been trying to investigate why I'm not able to print to the QL-810W, and see that the "Supported Models" chart in the readme say that this printer is not supported. Is this due to the version of the BRLMPrinterKit SDK (4.7.2) not supporting this printer? Do you know what is required to enable support for it? Do I need to use an earlier version of the SDK?

**Comment by rdlabo** [comment]
> see that the “Supported Models” chart in the readme says that this printer is not supported

I don't have a QL_810W and can't test it, and I'm not sure if it prints now that this plugin have changed support to Brother SDK v4. Of course, pull requests are welcome.

**Comment by rdlabo** [comment]
1. whether QL_810W can be detected
2. whether the printing paper supports it (this is relatively easy to handle)
3. whether printing is possible

The development process is as follows. Please note that it is impossible for me to verify these as I do not have the device in my possession.

**Comment by eugenedw** [comment]
I understand.

I'll check if it may be a paper issue. Based upon Brother's information, version 4 supports this model (https://support.brother.com/g/s/es/dev/en/mobilesdk/model/index.html?c=eu_ot&lang=en&navi=offall&comple=on&redirect=on).

Once I have a solution, and if it requires modification to the plugin, I'll generate the pull request.

**Comment by eugenedw** [comment]
Confirmed. Plugin does work with QL-810W. It turns out that I overlooked changing the default option from the readme:

```
    const defaultPrintSettings: BRLMPrintOptions = {
      modelName: BRLMPrinterModelName.QL_810W, // <--- changed the printer model
      labelName: BRLMPrinterLabelName.RollW62, // <--- left the label the same
      encodedImage: imagedata, // base64
      numberOfCopies: 1, // default 1
      autoCut: true, // default true
    };
```

No change to the plugin was required, though I suggest updating the readme to indicate that this printer version is supported.
