### ISSUE TITLE
Is it possible to connect ql-820nwb printer through bluetooth on andorid?

### ISSUE THREAD

**Issue by tmxkwkfgka** [rdlabo-team/capacitor-brotherprint#3]
I am trying to connect to ql-820nwb through bluetooth.

when I use searchBLEPrinter(), my ql-820nwb printer is not found.
but when I use https://github.com/don/BluetoothSerial which is cordova serial bluetooth library, my ql-820wb printer is found.

As I know ql 820nwb bluetooth is not bluetooth low energy but bluetooth serial.

Can ql-820nwb printer connect through bluetooth using your library?

**Comment by rdlabo** [comment]
Sorry, this repository is for private use and was not supported. However, due to requests, it will be supported starting with v6.2.0. If you still need it, please use it.

**Comment by AithaNishanth** [comment]
Hi @rdlabo can you please help me out in the android configuration I have followed all the steps as given, however when I try to search printer it is throwing an error, Failed to search printer uses permission denied. I am working on ionic angular.
