### ISSUE TITLE
invalid header path.

### ISSUE THREAD

**Issue by savageqm** [rdlabo-team/capacitor-brotherprint#5]
Could you explain what location is this? I download your repo but xcode tells me this path is invalid 
```header "../../../../../ios/App/Pods/BRLMPrinterKit/BRLMPrinterKit/BRLMPrinterKit.framework/Headers/BRLMPrinterKit.h"```

**Comment by ingageco** [comment]
@savageqm Did you resolve this? @rdlabo - any advice?
